ALTER TABLE assets ADD COLUMN count INT NOT NULL DEFAULT 0 AFTER tags;
ALTER TABLE assets ADD COLUMN access_level VARCHAR(20) NOT NULL DEFAULT 'public' AFTER count;
ALTER TABLE assets ADD COLUMN is_personal TINYINT(1) NOT NULL DEFAULT 1 AFTER access_level;
