apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "shortdrama-logs-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: 8
      logMessageField: message
      logLevelField: level
