apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogsV2:
        datasourceUid: elasticsearch
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        filterByTraceID: true
        filterBySpanID: true
