apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: shortdrama
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin: false
      enable_control: false
      enable_dev_mode: true
      enable_reuseport: true

    nginx_config:
      worker_processes: auto
      worker_connections: 16384
      client_max_body_size: 20m

    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml

    etcd:
      host: []
