# Multi-region overlay: EU West (Ireland)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shortdrama

resources:
  - ../../base
  - ../../infra
  - ../../services
  - ../../ingress
  - ../../monitoring

patches:
  - target:
      kind: ConfigMap
      name: shortdrama-config
    patch: |-
      - op: replace
        path: /data/REGION
        value: "eu-west-1"
      - op: replace
        path: /data/STORAGE_PUBLIC_ENDPOINT
        value: "https://s3.eu-west-1.amazonaws.com"
      - op: replace
        path: /data/STORAGE_REGION
        value: "eu-west-1"
      - op: replace
        path: /data/APP_ENV
        value: "production-eu"

images:
  - name: shortdrama/script-service
    newTag: latest-eu
  - name: shortdrama/storyboard-service
    newTag: latest-eu
  - name: shortdrama/content-service
    newTag: latest-eu
  - name: shortdrama/user-service
    newTag: latest-eu
  - name: shortdrama/llmhua-service
    newTag: latest-eu
  - name: shortdrama/video-service
    newTag: latest-eu
  - name: shortdrama/video-worker
    newTag: latest-eu
