"""Model Cache Layer — reduces redundant AI calls for billion-level concurrency.

Three-tier cache architecture:
    L1: Local (process memory) — sub-millisecond, hot character anchors
    L2: Redis — millisecond, template library + semantic cache
    L3: External AI API (DeepSeek/Seedance) — 100ms-60s, actual model inference

Cache hit ratios target:
    Character anchors: 80%+ (same character, same description → cached)
    Script templates:  60%+ (similar genre+style → template reuse)
    Image prompts:     40%+ (identical prompts → cached result URL)

LoRA Adapter Management:
    Hot adapters: pre-loaded on GPU (top 20 most-used characters)
    Warm adapters: loaded on demand, evicted LRU (next 100)
    Cold adapters: fetched from object storage on first use
"""
import hashlib
import json
import logging
import time
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ==================== L1: Local Memory Cache ====================

@dataclass
class CacheEntry:
    value: Any
    expires_at: float
    access_count: int = 0
    last_access: float = field(default_factory=time.time)


class L1MemoryCache:
    """LRU in-memory cache for ultra-hot items (sub-ms access)."""

    def __init__(self, max_size: int = 1000):
        self.max_size = max_size
        self._store: OrderedDict[str, CacheEntry] = OrderedDict()

    def get(self, key: str) -> Optional[Any]:
        entry = self._store.get(key)
        if entry is None:
            return None
        if time.time() > entry.expires_at:
            del self._store[key]
            return None
        entry.access_count += 1
        entry.last_access = time.time()
        # Move to end (most recently used)
        self._store.move_to_end(key)
        return entry.value

    def set(self, key: str, value: Any, ttl: int = 300):
        if key in self._store:
            self._store.move_to_end(key)
        else:
            while len(self._store) >= self.max_size:
                self._store.popitem(last=False)  # Evict LRU
        self._store[key] = CacheEntry(
            value=value,
            expires_at=time.time() + ttl,
        )

    def stats(self) -> Dict[str, Any]:
        return {
            "size": len(self._store),
            "max_size": self.max_size,
            "hit_rate": sum(e.access_count for e in self._store.values()),
        }


# ==================== Character Anchor Cache ====================

class CharacterAnchorCache:
    """Caches AI-generated character identity anchors to avoid redundant LLM calls.

    A character anchor is the 6-layer identity description generated by LLM:
      L1: 名字性别年龄
      L2: 外貌特征
      L3: 性格特质
      L4: 身份背景
      L5: 服装风格
      L6: 视觉提示词 (中/英)

    Cache key: md5(name + role + description + style + language)
    Hit ratio target: 80%+ (same character spec → same anchor)
    """

    def __init__(self, redis_client=None):
        self.l1 = L1MemoryCache(max_size=200)  # Hot: top 200 characters
        self.redis = redis_client               # L2: Redis
        self.namespace = "anchor"

    def _cache_key(self, name: str, role: str, description: str, style: str, language: str) -> str:
        content = f"{name}|{role}|{description[:200]}|{style}|{language}"
        return f"anchor:{hashlib.md5(content.encode()).hexdigest()[:16]}"

    async def get(self, name: str, role: str, description: str, style: str, language: str = "zh") -> Optional[Dict]:
        key = self._cache_key(name, role, description, style, language)

        # L1: Local memory
        cached = self.l1.get(key)
        if cached:
            logger.debug("L1 hit: character anchor %s", name)
            return cached

        # L2: Redis
        if self.redis:
            try:
                raw = await self.redis.get(key)
                if raw:
                    data = json.loads(raw)
                    self.l1.set(key, data, ttl=600)  # Promote to L1
                    logger.debug("L2 hit: character anchor %s", name)
                    return data
            except Exception as e:
                logger.error("Redis get failed for anchor %s: %s", key, e)

        return None

    async def set(self, name: str, role: str, description: str, style: str, language: str, data: Dict):
        key = self._cache_key(name, role, description, style, language)
        ttl = 86400  # 24h for character anchors

        # L1
        self.l1.set(key, data, ttl=600)

        # L2
        if self.redis:
            try:
                await self.redis.setex(key, ttl, json.dumps(data, ensure_ascii=False))
            except Exception as e:
                logger.error("Redis set failed for anchor %s: %s", key, e)

        logger.info("Cached character anchor: %s (key=%s)", name, key)


# ==================== Short Drama Template Library ====================

class TemplateLibrary:
    """Pre-built Short Drama templates to reduce LLM generation from scratch.

    Templates are parameterized story structures that can be filled with
    user-provided characters and settings — avoiding full LLM generation.

    Categories:
        - 霸总 (CEO romance)
        - 逆袭 (Underdog comeback)
        - 悬疑 (Mystery/thriller)
        - 甜宠 (Sweet romance)
        - 古装 (Historical)
        - 都市 (Urban)
    """

    # Template structure: {genre: {style: [template]}}
    # Each template has: name, outline, scene_count, character_archetypes, plot_beats
    TEMPLATES: Dict[str, List[Dict]] = {
        "霸总": [
            {
                "name": "契约婚姻",
                "description": "女主因家族债务被迫嫁给霸总，从互相折磨到真心相爱",
                "episodes": 80,
                "scene_types": ["办公室", "豪宅", "宴会厅", "医院", "机场"],
                "character_slots": {
                    "男主": {"type": "霸总", "age_range": [28, 35]},
                    "女主": {"type": "灰姑娘", "age_range": [22, 28]},
                    "女二": {"type": "白月光/心机女", "age_range": [25, 30]},
                    "男二": {"type": "温柔守护者", "age_range": [25, 32]},
                },
                "plot_beats": [
                    "被迫相遇 → 契约签订",
                    "同居磨合 → 暗生情愫",
                    "女二破坏 → 误会分离",
                    "危机时刻 → 男主拯救",
                    "真相大白 → 破镜重圆",
                ],
            },
        ],
        "逆袭": [
            {
                "name": "赘婿翻身",
                "description": "卑微赘婿隐藏真实身份，最终逆袭打脸所有人",
                "episodes": 100,
                "scene_types": ["豪门客厅", "公司", "餐厅", "拍卖会", "工地"],
                "character_slots": {
                    "男主": {"type": "隐藏强者", "age_range": [25, 35]},
                    "女主": {"type": "豪门千金", "age_range": [22, 28]},
                    "反派": {"type": "势利眼亲戚", "age_range": [35, 55]},
                },
                "plot_beats": [
                    "忍辱负重 → 众人嘲讽",
                    "身份显露 → 初次震惊",
                    "层层揭秘 → 持续打脸",
                    "最终对决 → 真相大白",
                    "登顶巅峰 → 大团圆",
                ],
            },
        ],
        "甜宠": [
            {
                "name": "先婚后爱",
                "description": "因误会或协议结婚，从冷漠到甜蜜的恋爱过程",
                "episodes": 60,
                "scene_types": ["婚房", "咖啡厅", "游乐园", "海边", "医院"],
                "character_slots": {
                    "男主": {"type": "高冷/温柔", "age_range": [26, 33]},
                    "女主": {"type": "活泼/倔强", "age_range": [22, 28]},
                },
                "plot_beats": [
                    "被迫结婚 → 冷漠相处",
                    "意外事件 → 态度转变",
                    "情敌出现 → 男主吃醋",
                    "互诉真心 → 甜蜜日常",
                    "婚礼重办 → 完美结局",
                ],
            },
        ],
    }

    @classmethod
    def find_matching(
        cls,
        genre: str,
        style: str = "",
        episode_count: int = 0,
    ) -> List[Dict]:
        """Find templates matching the given criteria."""
        templates = cls.TEMPLATES.get(genre, [])
        if not templates:
            # Try fuzzy match
            for key in cls.TEMPLATES:
                if genre in key or key in genre:
                    templates = cls.TEMPLATES[key]
                    break

        # Filter by episode count (±20%)
        if episode_count > 0:
            filtered = []
            for t in templates:
                if abs(t["episodes"] - episode_count) / episode_count < 0.3:
                    filtered.append(t)
            if filtered:
                templates = filtered

        return templates

    @classmethod
    def apply_template(
        cls,
        template: Dict,
        characters: Dict[str, str],
        customizations: Optional[Dict] = None,
    ) -> Dict:
        """Fill a template with user-provided characters and customizations."""
        result = {
            "name": template["name"],
            "description": template["description"],
            "episodes": template["episodes"],
            "scene_types": template["scene_types"],
            "plot_beats": template["plot_beats"],
            "characters": {},
        }

        # Substitute character slots with actual names
        for slot_key, slot_info in template["character_slots"].items():
            actual_name = characters.get(slot_key, slot_key)
            result["characters"][slot_key] = {
                "name": actual_name,
                "type": slot_info["type"],
                "age_range": slot_info["age_range"],
            }

        if customizations:
            for key, value in customizations.items():
                if key in result:
                    result[key] = value

        return result


# ==================== LoRA Adapter Manager ====================

class LoRAAdapterManager:
    """Manages LoRA adapters for character-consistent image/video generation.

    Lifecycle:
        HOT  (GPU memory):   Top 20 most-used characters, always loaded
        WARM (CPU memory):   Next 100 characters, loaded on demand
        COLD (Object storage): All others, fetched on first reference

    LoRA weights are stored in MinIO/S3 under: lora/{character_id}/adapter.safetensors
    """

    def __init__(self, storage_client=None):
        self.storage = storage_client
        self.hot_adapters: OrderedDict[str, Any] = OrderedDict()   # Max 20
        self.warm_adapters: OrderedDict[str, Any] = OrderedDict()  # Max 100
        self.access_counter: Dict[str, int] = {}
        self.max_hot = 20
        self.max_warm = 100

    def record_access(self, character_id: str):
        """Record a character access for LRU tracking."""
        self.access_counter[character_id] = self.access_counter.get(character_id, 0) + 1

    def get_hot_characters(self) -> List[str]:
        """Return the top-N most-accessed character IDs."""
        sorted_chars = sorted(
            self.access_counter.items(),
            key=lambda x: x[1],
            reverse=True,
        )
        return [char_id for char_id, _ in sorted_chars[:self.max_hot]]

    async def load_adapter(self, character_id: str) -> Optional[Any]:
        """Load a LoRA adapter, promoting through the cache tiers.

        Returns:
            The adapter object, or None if not found.
        """
        # Check hot tier
        if character_id in self.hot_adapters:
            self.hot_adapters.move_to_end(character_id)
            return self.hot_adapters[character_id]

        # Check warm tier
        if character_id in self.warm_adapters:
            adapter = self.warm_adapters.pop(character_id)
            # Promote to hot
            await self._promote_to_hot(character_id, adapter)
            return adapter

        # Fetch from cold (object storage)
        adapter = await self._fetch_from_storage(character_id)
        if adapter:
            await self._promote_to_warm(character_id, adapter)
            return adapter

        return None

    async def _promote_to_hot(self, character_id: str, adapter: Any):
        """Promote an adapter to the hot tier, evicting LRU if needed."""
        while len(self.hot_adapters) >= self.max_hot:
            evicted_id, evicted_adapter = self.hot_adapters.popitem(last=False)
            await self._promote_to_warm(evicted_id, evicted_adapter)
        self.hot_adapters[character_id] = adapter

    async def _promote_to_warm(self, character_id: str, adapter: Any):
        """Demote an adapter to the warm tier."""
        while len(self.warm_adapters) >= self.max_warm:
            evicted_id, _ = self.warm_adapters.popitem(last=False)
            logger.debug("Evicted LoRA adapter from warm: %s", evicted_id)
        self.warm_adapters[character_id] = adapter

    async def _fetch_from_storage(self, character_id: str) -> Optional[Any]:
        """Fetch LoRA adapter weights from object storage."""
        if not self.storage:
            return None
        try:
            object_key = f"lora/{character_id}/adapter.safetensors"
            # data = await self.storage.download_bytes(object_key)
            # For now, return a placeholder — actual loading depends on the inference engine
            logger.info("Fetched LoRA adapter from cold: %s", object_key)
            return {"character_id": character_id, "source": "storage"}
        except Exception as e:
            logger.error("Failed to fetch LoRA adapter %s: %s", character_id, e)
            return None


# ==================== Unified Model Cache ====================

class ModelCache:
    """Unified three-tier model cache for AI inference optimization.

    Components:
        - CharacterAnchorCache: Avoids redundant LLM calls for character design
        - TemplateLibrary: Pre-built drama structures, fill in characters
        - LoRAAdapterManager: Tiered LoRA loading (GPU→CPU→Storage)

    Usage:
        cache = await get_model_cache()
        # Check character anchor cache
        anchor = await cache.anchors.get("Hero", "protagonist", "brave warrior", "写实", "zh")
        if anchor is None:
            anchor = await call_llm_for_anchor(...)
            await cache.anchors.set("Hero", "protagonist", "brave warrior", "写实", "zh", anchor)
    """

    def __init__(self, redis_client=None, storage_client=None):
        self.anchors = CharacterAnchorCache(redis_client)
        self.templates = TemplateLibrary()
        self.lora = LoRAAdapterManager(storage_client)
        self.l1 = L1MemoryCache(max_size=500)

    def stats(self) -> Dict[str, Any]:
        return {
            "l1": self.l1.stats(),
            "lora_hot": len(self.lora.hot_adapters),
            "lora_warm": len(self.lora.warm_adapters),
            "top_characters": self.lora.get_hot_characters()[:10],
        }


# Global singleton
_model_cache: Optional[ModelCache] = None


async def get_model_cache() -> ModelCache:
    global _model_cache
    if _model_cache is None:
        from app.core.config import settings
        import redis.asyncio as redis
        try:
            r = redis.Redis(
                host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                password=settings.REDIS_PASSWORD,
                db=settings.REDIS_DB,
                decode_responses=True,
            )
        except Exception:
            r = None
        _model_cache = ModelCache(redis_client=r)
        logger.info("ModelCache initialized (3-tier: L1 memory → L2 Redis → L3 API)")
    return _model_cache


async def close_model_cache():
    global _model_cache
    _model_cache = None
    logger.info("ModelCache closed")
